# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/vga.xdc

# IP: ip/data_memory1/data_memory1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==data_memory1 || ORIG_REF_NAME==data_memory1} -quiet] -quiet
