# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param chipscope.maxJobs 2
set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7a35tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir E:/Vivado_project/final/new/new.cache/wt [current_project]
set_property parent.project_path E:/Vivado_project/final/new/new.xpr [current_project]
set_property XPM_LIBRARIES XPM_CDC [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths e:/Vivado_project/final/data_memory1/data_memory1.srcs/sources_1/new [current_project]
update_ip_catalog
set_property ip_output_repo e:/Vivado_project/final/new/new.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files E:/Vivado_project/final/new/new.srcs/sources_1/ip/instr_memory.coe
read_verilog -library xil_defaultlib {
  E:/Vivado_project/final/new/new.srcs/sources_1/new/alu.v
  E:/Vivado_project/final/new/new.srcs/sources_1/new/branch_judge.v
  E:/Vivado_project/final/new/new.srcs/sources_1/new/define.v
  E:/Vivado_project/final/new/new.srcs/sources_1/new/control.v
  E:/Vivado_project/final/new/new.srcs/sources_1/new/datapath.v
  E:/Vivado_project/final/new/new.srcs/sources_1/new/ex_mem_regs.v
  E:/Vivado_project/final/new/new.srcs/sources_1/new/ex_stage.v
  E:/Vivado_project/final/new/new.srcs/sources_1/new/forward_units.v
  E:/Vivado_project/final/new/new.srcs/sources_1/new/id_ex_regs.v
  E:/Vivado_project/final/new/new.srcs/sources_1/new/id_stage.v
  E:/Vivado_project/final/new/new.srcs/sources_1/new/if_id_regs.v
  E:/Vivado_project/final/new/new.srcs/sources_1/new/if_stage.v
  E:/Vivado_project/final/new/new.srcs/sources_1/new/instr_decode.v
  E:/Vivado_project/final/new/new.srcs/sources_1/new/mem_wb_regs.v
  E:/Vivado_project/final/new/new.srcs/sources_1/new/men_stage.v
  E:/Vivado_project/final/new/new.srcs/sources_1/new/mux.v
  E:/Vivado_project/final/new/new.srcs/sources_1/new/mux3_1.v
  E:/Vivado_project/final/new/new.srcs/sources_1/new/pc_reg.v
  E:/Vivado_project/final/new/new.srcs/sources_1/new/registers.v
  E:/Vivado_project/final/new/new.srcs/sources_1/new/riscv.v
  E:/Vivado_project/final/new/new.srcs/sources_1/new/vga.v
  E:/Vivado_project/final/new/new.srcs/sources_1/new/wb_stage.v
  E:/Vivado_project/final/new/new.srcs/sources_1/new/riscv_top.v
}
read_ip -quiet E:/Vivado_project/final/new/new.srcs/sources_1/ip/data_memory1/data_memory1.xci

read_ip -quiet E:/Vivado_project/final/new/new.srcs/sources_1/ip/clk_wiz/clk_wiz.xci
set_property used_in_implementation false [get_files -all e:/Vivado_project/final/new/new.srcs/sources_1/ip/clk_wiz/clk_wiz_board.xdc]
set_property used_in_implementation false [get_files -all e:/Vivado_project/final/new/new.srcs/sources_1/ip/clk_wiz/clk_wiz.xdc]
set_property used_in_implementation false [get_files -all e:/Vivado_project/final/new/new.srcs/sources_1/ip/clk_wiz/clk_wiz_ooc.xdc]

read_ip -quiet e:/Vivado_project/final/new/new.srcs/sources_1/ip/dist_mem_gen_0/dist_mem_gen_0.xci
set_property used_in_implementation false [get_files -all e:/Vivado_project/final/new/new.srcs/sources_1/ip/dist_mem_gen_0/dist_mem_gen_0_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc E:/Vivado_project/final/new/new.srcs/constrs_1/new/vga.xdc
set_property used_in_implementation false [get_files E:/Vivado_project/final/new/new.srcs/constrs_1/new/vga.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top riscv_top -part xc7a35tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef riscv_top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file riscv_top_utilization_synth.rpt -pb riscv_top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
