# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_resetJobStats
    rt::HARTNDb_resetSystemStats
    rt::HARTNDb_startSystemStats
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "C:/Users/Xuefeng/Desktop/sys 3.0/.Xil/Vivado-13412-Desktop-Windows/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file delete -force $::env(RT_TMP)
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    set rt::partid xc7a35tcsg324-1
     file delete -force synth_hints.os

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common_vhdl.tcl
    set rt::defaultWorkLibName xil_defaultlib

    set rt::useElabCache false
    if {$rt::useElabCache == false} {
      rt::read_verilog -sv -include {
    {C:/Users/Xuefeng/Desktop/sys 3.0/new.srcs/sources_1/ip/clk_wiz}
    {C:/Users/Xuefeng/Desktop/sys 3.0/new.srcs/sources_1/ip/dist_mem_gen_0}
  } C:/ProgramData/Xilinx/Vivado/2019.2/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv
      rt::read_verilog -include {
    {C:/Users/Xuefeng/Desktop/sys 3.0/new.srcs/sources_1/ip/clk_wiz}
    {C:/Users/Xuefeng/Desktop/sys 3.0/new.srcs/sources_1/ip/dist_mem_gen_0}
  } {
      {C:/Users/Xuefeng/Desktop/sys 3.0/.Xil/Vivado-13412-Desktop-Windows/realtime/data_memory1_stub.v}
      {C:/Users/Xuefeng/Desktop/sys 3.0/.Xil/Vivado-13412-Desktop-Windows/realtime/clk_wiz_stub.v}
      {C:/Users/Xuefeng/Desktop/sys 3.0/.Xil/Vivado-13412-Desktop-Windows/realtime/dist_mem_gen_0_stub.v}
      {C:/Users/Xuefeng/Desktop/sys 3.0/new.srcs/sources_1/new/alu.v}
      {C:/Users/Xuefeng/Desktop/sys 3.0/new.srcs/sources_1/new/branch_judge.v}
      {C:/Users/Xuefeng/Desktop/sys 3.0/new.srcs/sources_1/new/define.v}
      {C:/Users/Xuefeng/Desktop/sys 3.0/new.srcs/sources_1/new/control.v}
      {C:/Users/Xuefeng/Desktop/sys 3.0/new.srcs/sources_1/new/datapath.v}
      {C:/Users/Xuefeng/Desktop/sys 3.0/new.srcs/sources_1/new/ex_mem_regs.v}
      {C:/Users/Xuefeng/Desktop/sys 3.0/new.srcs/sources_1/new/ex_stage.v}
      {C:/Users/Xuefeng/Desktop/sys 3.0/new.srcs/sources_1/new/forward_units.v}
      {C:/Users/Xuefeng/Desktop/sys 3.0/new.srcs/sources_1/new/id_ex_regs.v}
      {C:/Users/Xuefeng/Desktop/sys 3.0/new.srcs/sources_1/new/id_stage.v}
      {C:/Users/Xuefeng/Desktop/sys 3.0/new.srcs/sources_1/new/if_id_regs.v}
      {C:/Users/Xuefeng/Desktop/sys 3.0/new.srcs/sources_1/new/if_stage.v}
      {C:/Users/Xuefeng/Desktop/sys 3.0/new.srcs/sources_1/new/instr_decode.v}
      {C:/Users/Xuefeng/Desktop/sys 3.0/new.srcs/sources_1/new/mem_wb_regs.v}
      {C:/Users/Xuefeng/Desktop/sys 3.0/new.srcs/sources_1/new/men_stage.v}
      {C:/Users/Xuefeng/Desktop/sys 3.0/new.srcs/sources_1/new/mux.v}
      {C:/Users/Xuefeng/Desktop/sys 3.0/new.srcs/sources_1/new/mux3_1.v}
      {C:/Users/Xuefeng/Desktop/sys 3.0/new.srcs/sources_1/new/pc_reg.v}
      {C:/Users/Xuefeng/Desktop/sys 3.0/new.srcs/sources_1/new/registers.v}
      {C:/Users/Xuefeng/Desktop/sys 3.0/new.srcs/sources_1/new/riscv.v}
      {C:/Users/Xuefeng/Desktop/sys 3.0/new.srcs/sources_1/new/vga.v}
      {C:/Users/Xuefeng/Desktop/sys 3.0/new.srcs/sources_1/new/wb_stage.v}
      {C:/Users/Xuefeng/Desktop/sys 3.0/new.srcs/sources_1/new/riscv_top.v}
    }
      rt::read_vhdl -lib xpm C:/ProgramData/Xilinx/Vivado/2019.2/data/ip/xpm/xpm_VCOMP.vhd
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification false
    set rt::top riscv_top
    rt::set_parameter enableIncremental true
    set rt::reportTiming false
    rt::set_parameter elaborateOnly true
    rt::set_parameter elaborateRtl true
    rt::set_parameter eliminateRedundantBitOperator false
    rt::set_parameter elaborateRtlOnlyFlow true
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter merge_flipflops true
    rt::set_parameter srlDepthThreshold 3
    rt::set_parameter rstSrlDepthThreshold 4
# MODE: 
    rt::set_parameter webTalkPath {}
    rt::set_parameter enableSplitFlowPath "C:/Users/Xuefeng/Desktop/sys 3.0/.Xil/Vivado-13412-Desktop-Windows/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
        set oldMIITMVal [rt::get_parameter maxInputIncreaseToMerge]; rt::set_parameter maxInputIncreaseToMerge 1000
        set oldCDPCRL [rt::get_parameter createDfgPartConstrRecurLimit]; rt::set_parameter createDfgPartConstrRecurLimit 1
        $rt::db readXRFFile
      rt::run_rtlelab -module $rt::top
        rt::set_parameter maxInputIncreaseToMerge $oldMIITMVal
        rt::set_parameter createDfgPartConstrRecurLimit $oldCDPCRL
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    if { $rt::flowresult == 1 } { return -code error }


  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  rt::set_parameter helper_shm_key "" 
    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }

    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
  $rt::db resetHdlParse
  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  return -code "error" $rt::result
}
